

services:
  # Gateway Service
  gateway-service:
    build:
      context: ./services/gateway-service
    container_name: gateway-service
    ports:
      - "3000:3000"
    networks:
      - trd-network
    depends_on:
      - auth-service
      - customer-service
      - notification-service

  # Auth Service
  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth-service
    ports:
      - "4005:4005"
    networks:
      - trd-network
    depends_on:
      - auth-db
      - message-broker

  # Customer Service
  customer-service:
    build:
      context: ./services/customer-service
    container_name: customer-service
    ports:
      - "4000:4000"
    networks:
      - trd-network
    depends_on:
      - customers-db
      - message-broker

  # Notification Service
  notification-service:
    build:
      context: ./services/notification-service
    container_name: notification-service
    ports:
      - "4002:4002"
    networks:
      - trd-network
    depends_on:
      - message-broker

  # Message Broker (RabbitMQ)
  message-broker:
    image: rabbitmq:management
    container_name: message-broker
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - trd-network

  # Auth Database (MariaDB)
  auth-db:
    image: mariadb:10.7
    container_name: auth-db
    restart: always
    command: --bind-address=0.0.0.0 --port=3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: authpassword
      MYSQL_TCP_PORT: 3306
    ports:
      - "3307:3306"
    volumes:
      - auth-db-data:/var/lib/mysql
      - ./services/auth-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - trd-network
    healthcheck:  # Correction d'indentation ici
      test: mysqladmin ping -u root -p$$MYSQL_ROOT_PASSWORD
      interval: 5s
      timeout: 10s
      retries: 10


  # Customers Database (MariaDB)
  customers-db:
    image: mariadb:10.7
    container_name: customers-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: customers_db
      MYSQL_USER: customers_user
      MYSQL_PASSWORD: customerspassword
    ports:
      - "3308:3306"
    volumes:
      - customers-db-data:/var/lib/mysql
      - ./services/customer-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - trd-network

volumes:
  auth-db-data:
  customers-db-data:

networks:
  trd-network:
    driver: bridge
